spring:
  # H2 Database ??
  datasource:
    driver-class-name: org.postgresql.Driver # org.h2.Driver
    url: 'jdbc:postgresql://localhost:5432/gdsc_forum'     # H2 DB (In-Memory Mode)
    # url: 'jdbc:h2:~/test'     # H2 DB (Embedded Mode)
    username: gdsc-forum              # H2 DB ID
    password: gdsc-forum              # H2 DB PW

  # H2 Console
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  # JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none        # (none, create, create-drop, update, validate)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect    # Dialect: 데이터베이스에 대한 특정 SQL 문법과 데이터 타입 매핑에 대한 규칙을 제공
        format_sql: true      # SQL 쿼리를 포맷팅하여 출력할지 여부 설정
        show_sql: true        # SQL 쿼리를 출력할지 여부 설정

  sql:
    init:
      mode: never
      schema-locations: classpath:db-init-scripts/schema.sql
      data-locations: classpath:db-init-scripts/data.sql

app:
  jwt:
    accessTokenValidMS: 3600000  # 1시간
    refreshTokenValidMS: 604800000  # 7일

server:
  # 서버 안전하게 종료하기
  shutdown: graceful